name: Code Inspection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v4.0.2
        with:
          path: ~/work/_temp/_github_home/cache
          key: ${{ runner.os }}-qodana-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-qodana-${{ github.ref }}
            ${{ runner.os }}-qodana-
      - uses: docker://jetbrains/qodana
        with:
          args: --cache-dir=/github/home/cache --results-dir=/github/workspace/qodana --save-report --report-dir=/github/workspace/qodana/report
      - uses: actions/upload-artifact@v2
        with:
          path: qodana
